server:
  port: 8003

spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    #url: jdbc:oracle:thin:@43.200.33.166:1522/xe
    #url: jdbc:oracle:thin:@192.168.0.24:1522/xe  로컬에 올릴때는 포트 번호 바꿔야 함.. doker에 올리셨던???
    url: jdbc:oracle:thin:@localhost:1521/xe
    username: REST
    password: REST
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  web:
    resources:
      static-locations: classpath:/artimgs/

# 이미지 저장할 위치와 응답할 때 이미지 주소 세팅
image:
  # WebConfig에 세팅
  #add-resource-locations: classpath:/static/artimgs/
  #add-resource-handler: /artimgs/**

  add-resource-locations: /artimgs/
  add-resource-handler: /artimgs/**


  # artService에 세팅
  #image-dir: src/main/resources/static/artimgs/
  image-dir: /artimgs/
  #image-url: http://43.200.33.166:8090/artimgs/
  #image-url: http://192.168.0.24:8090/artimgs/
  image-url: http://localhost:8003/artimgs/

# HS512 알고리즘을 사용할 것이기 때문에 512bit, 즉 64byte 이상의 secret key를 사용
# Secret 값은 특정 문자열을 Base64 로 인코딩한 값 사용
jwt:
  secret: dW5pLXJlYWN0LW5naW54LXNwcmluZy1ib290LWp3dC1vcmFjbGUtZG9ja2VyLWVjMi1yZWFjdC1uZ25peC1zcHJpbmctYm9vdC1qd3Qtb3JhY2xlLWRvY2tlci1lYzIK


mybatis:
  # mapper.xml location Setting
  mapper-locations: mybatis/mapper/*.xml
  # alias Setting
  type-aliases-package: com.example.reactpro
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    root: info


